export const bookSummaries: Record<string, string> = {
  // Old Testament
  gn: "The book of beginnings, describing creation, the fall of humanity, and God's covenant with Abraham, Isaac, and Jacob.",
  ex: "The story of Israel's deliverance from Egyptian slavery and the giving of the Law at Mount Sinai.",
  lv: 'Instructions for worship, sacrifices, and holy living for the people of Israel.',
  nm: 'The wilderness wanderings of Israel and preparation for entering the Promised Land.',
  dt: "Moses' final speeches to Israel, reviewing the Law and preparing them for life in Canaan.",
  js: "The conquest and division of the Promised Land under Joshua's leadership.",
  jz: 'The cycle of sin, oppression, and deliverance during the time of the judges.',
  rt: 'A story of loyalty and redemption set during the time of the judges.',
  '1sm':
    'The transition from judges to monarchy, featuring Samuel, Saul, and David.',
  '2sm': 'The reign of King David, his victories, and his failures.',
  '1rs':
    'The reign of Solomon and the division of the kingdom into Israel and Judah.',
  '2rs': 'The history of the divided kingdoms until their exile.',
  '1cr':
    "A retelling of Israel's history from Adam to David, emphasizing worship and the temple.",
  '2cr':
    'The history of Judah from Solomon to the exile, focusing on temple worship.',
  ed: 'The return from Babylonian exile and the rebuilding of the temple.',
  ne: "The rebuilding of Jerusalem's walls and spiritual renewal under Nehemiah.",
  et: "God's providential care for His people through Queen Esther in Persia.",
  jb: "The story of Job's suffering and his dialogue with friends about suffering and faith.",
  sl: 'A collection of songs, prayers, and poems expressing worship and life experiences.',
  pv: 'Practical wisdom for daily living and making godly choices.',
  ec: 'Reflections on the meaning of life and the pursuit of wisdom.',
  ct: 'A poetic celebration of love between a bride and groom.',
  is: 'Prophecies of judgment and salvation, including messianic promises.',
  jr: 'Warnings of judgment against Judah and promises of restoration.',
  lm: 'Poetic laments over the destruction of Jerusalem.',
  ez: "Visions of God's glory, judgment, and the restoration of Israel.",
  dn: 'Stories of faithfulness in exile and apocalyptic visions of the future.',
  os: "God's unfailing love despite Israel's unfaithfulness, using marriage imagery.",
  jl: "A call to repentance in light of the coming 'Day of the Lord.'",
  am: "A shepherd's call for social justice and true worship.",
  ob: 'Judgment against Edom for their pride and mistreatment of Israel.',
  jn: "The story of a reluctant prophet and God's compassion for all nations.",
  mq: 'Prophecies of judgment and hope, including the promise of a ruler from Bethlehem.',
  na: "God's judgment against the Assyrian city of Nineveh.",
  hc: "A prophet's dialogue with God about justice and faith during difficult times.",
  sf: 'Warning of judgment and promise of restoration for the humble.',
  ag: 'Encouragement to rebuild the temple after the exile.',
  zc: 'Visions and prophecies encouraging the post-exilic community.',
  ml: "God's love for Israel and call to faithfulness in worship and relationships.",

  // New Testament
  mt: 'The Gospel presenting Jesus as the promised Messiah and King of the Jews.',
  mc: 'The Gospel emphasizing Jesus as the suffering Servant who came to serve.',
  lc: "The Gospel highlighting Jesus' compassion for all people, especially the marginalized.",
  jo: 'The Gospel revealing Jesus as the divine Son of God and the Word made flesh.',
  at: "The spread of the early church from Jerusalem to Rome through the Holy Spirit's power.",
  rm: "Paul's systematic explanation of salvation by faith and Christian living.",
  '1co':
    "Paul's instructions to address divisions and moral issues in the Corinthian church.",
  '2co': "Paul's defense of his apostolic ministry and call for church unity.",
  gl: "Paul's passionate defense of salvation by faith alone, not by works of the law.",
  ef: "The believer's position in Christ and practical instructions for church unity.",
  fp: "Paul's letter of joy and encouragement written from prison.",
  cl: 'The supremacy of Christ and warnings against false teachings.',
  '1ts': 'Encouragement and instruction for a young church facing persecution.',
  '2ts':
    "Clarification about Christ's second coming and exhortation to perseverance.",
  '1tm': 'Instructions for church leadership and organization.',
  '2tm':
    "Paul's final letter, encouraging Timothy to faithfulness in ministry.",
  tt: 'Instructions for church leadership and Christian conduct.',
  fm: 'A personal appeal for forgiveness and reconciliation.',
  hb: 'The superiority of Christ over the old covenant and call to perseverance.',
  tg: 'Practical wisdom for Christian living and the relationship between faith and works.',
  '1pe': 'Encouragement for Christians suffering persecution.',
  '2pe': "Warning against false teachers and reminder of Christ's return.",
  '1jo': 'Assurance of salvation and the importance of love and truth.',
  '2jo': "Warning against false teachers who deny Christ's incarnation.",
  '3jo': 'Commendation of hospitality and warning against church tyranny.',
  jd: 'Warning against false teachers and encouragement to contend for the faith.',
  rv: "Apocalyptic visions of Christ's victory and the establishment of God's eternal kingdom.",
}
