export const bookSummaries: Record<string, string> = {
  // Antigo Testamento
  gn: 'O livro dos começos, descrevendo a criação, a queda da humanidade e a aliança de Deus com Abraão, Isaque e Jacó.',
  ex: 'A história da libertação de Israel da escravidão egípcia e a entrega da Lei no Monte Sinai.',
  lv: 'Instruções para adoração, sacrifícios e vida santa para o povo de Israel.',
  nm: 'As peregrinações de Israel no deserto e a preparação para entrar na Terra Prometida.',
  dt: 'Os discursos finais de Moisés a Israel, revisando a Lei e preparando-os para a vida em Canaã.',
  js: 'A conquista e divisão da Terra Prometida sob a liderança de Josué.',
  jz: 'O ciclo de pecado, opressão e libertação durante o tempo dos juízes.',
  rt: 'Uma história de lealdade e redenção ambientada durante o tempo dos juízes.',
  '1sm':
    'A transição dos juízes para a monarquia, apresentando Samuel, Saul e Davi.',
  '2sm': 'O reinado do Rei Davi, suas vitórias e seus fracassos.',
  '1rs': 'O reinado de Salomão e a divisão do reino em Israel e Judá.',
  '2rs': 'A história dos reinos divididos até o exílio.',
  '1cr':
    'Uma recontagem da história de Israel de Adão a Davi, enfatizando a adoração e o templo.',
  '2cr':
    'A história de Judá de Salomão ao exílio, focando na adoração no templo.',
  ed: 'O retorno do exílio babilônico e a reconstrução do templo.',
  ne: 'A reconstrução dos muros de Jerusalém e renovação espiritual sob Neemias.',
  et: 'O cuidado providencial de Deus por Seu povo através da Rainha Ester na Pérsia.',
  jb: 'A história do sofrimento de Jó e seu diálogo com amigos sobre sofrimento e fé.',
  sl: 'Uma coleção de cânticos, orações e poemas expressando adoração e experiências de vida.',
  pv: 'Sabedoria prática para a vida diária e para fazer escolhas piedosas.',
  ec: 'Reflexões sobre o significado da vida e a busca pela sabedoria.',
  ct: 'Uma celebração poética do amor entre uma noiva e um noivo.',
  is: 'Profecias de julgamento e salvação, incluindo promessas messiânicas.',
  jr: 'Advertências de julgamento contra Judá e promessas de restauração.',
  lm: 'Lamentos poéticos sobre a destruição de Jerusalém.',
  ez: 'Visões da glória de Deus, julgamento e restauração de Israel.',
  dn: 'Histórias de fidelidade no exílio e visões apocalípticas do futuro.',
  os: 'O amor inabalável de Deus apesar da infidelidade de Israel, usando imagens de casamento.',
  jl: "Um chamado ao arrependimento à luz da vinda do 'Dia do Senhor'.",
  am: 'O chamado de um pastor por justiça social e adoração verdadeira.',
  ob: 'Julgamento contra Edom por seu orgulho e maus tratos a Israel.',
  jn: 'A história de um profeta relutante e a compaixão de Deus por todas as nações.',
  mq: 'Profecias de julgamento e esperança, incluindo a promessa de um governante de Belém.',
  na: 'O julgamento de Deus contra a cidade assíria de Nínive.',
  hc: 'O diálogo de um profeta com Deus sobre justiça e fé durante tempos difíceis.',
  sf: 'Advertência de julgamento e promessa de restauração para os humildes.',
  ag: 'Encorajamento para reconstruir o templo após o exílio.',
  zc: 'Visões e profecias encorajando a comunidade pós-exílica.',
  ml: 'O amor de Deus por Israel e chamado à fidelidade na adoração e relacionamentos.',

  // Novo Testamento
  mt: 'O Evangelho apresentando Jesus como o Messias prometido e Rei dos judeus.',
  mc: 'O Evangelho enfatizando Jesus como o Servo sofredor que veio para servir.',
  lc: 'O Evangelho destacando a compaixão de Jesus por todas as pessoas, especialmente os marginalizados.',
  jo: 'O Evangelho revelando Jesus como o Filho divino de Deus e o Verbo feito carne.',
  at: 'A expansão da igreja primitiva de Jerusalém a Roma através do poder do Espírito Santo.',
  rm: 'A explicação sistemática de Paulo sobre salvação pela fé e vida cristã.',
  '1co':
    'As instruções de Paulo para lidar com divisões e questões morais na igreja coríntia.',
  '2co':
    'A defesa de Paulo de seu ministério apostólico e chamado para unidade da igreja.',
  gl: 'A defesa apaixonada de Paulo da salvação somente pela fé, não pelas obras da lei.',
  ef: 'A posição do crente em Cristo e instruções práticas para unidade da igreja.',
  fp: 'A carta de Paulo sobre alegria e encorajamento escrita da prisão.',
  cl: 'A supremacia de Cristo e advertências contra falsos ensinos.',
  '1ts':
    'Encorajamento e instrução para uma igreja jovem enfrentando perseguição.',
  '2ts':
    'Esclarecimento sobre a segunda vinda de Cristo e exortação à perseverança.',
  '1tm': 'Instruções para liderança e organização da igreja.',
  '2tm':
    'A última carta de Paulo, encorajando Timóteo à fidelidade no ministério.',
  tt: 'Instruções para liderança da igreja e conduta cristã.',
  fm: 'Um apelo pessoal por perdão e reconciliação.',
  hb: 'A superioridade de Cristo sobre a antiga aliança e chamado à perseverança.',
  tg: 'Sabedoria prática para vida cristã e a relação entre fé e obras.',
  '1pe': 'Encorajamento para cristãos sofrendo perseguição.',
  '2pe': 'Advertência contra falsos mestres e lembrete do retorno de Cristo.',
  '1jo': 'Certeza de salvação e a importância do amor e da verdade.',
  '2jo': 'Advertência contra falsos mestres que negam a encarnação de Cristo.',
  '3jo': 'Elogio da hospitalidade e advertência contra tirania na igreja.',
  jd: 'Advertência contra falsos mestres e encorajamento para batalhar pela fé.',
  rv: 'Visões apocalípticas da vitória de Cristo e estabelecimento do reino eterno de Deus.',
}
