export const scriptureMap = {
  gn: { 'pt-br': 'Gênesis', en: 'Genesis' },
  ex: { 'pt-br': 'Êxodo', en: 'Exodus' },
  lv: { 'pt-br': 'Levítico', en: 'Leviticus' },
  nm: { 'pt-br': 'Números', en: 'Numbers' },
  dt: { 'pt-br': 'Deuteronômio', en: 'Deuteronomy' },
  js: { 'pt-br': 'Josué', en: 'Joshua' },
  jz: { 'pt-br': 'Juízes', en: 'Judges' },
  rt: { 'pt-br': 'Rute', en: 'Ruth' },
  '1sm': { 'pt-br': '1 Samuel', en: '1 Samuel' },
  '2sm': { 'pt-br': '2 Samuel', en: '2 Samuel' },
  '1rs': { 'pt-br': '1 Reis', en: '1 Kings' },
  '2rs': { 'pt-br': '2 Reis', en: '2 Kings' },
  '1cr': { 'pt-br': '1 Crônicas', en: '1 Chronicles' },
  '2cr': { 'pt-br': '2 Crônicas', en: '2 Chronicles' },
  ed: { 'pt-br': 'Esdras', en: 'Ezra' },
  ne: { 'pt-br': 'Neemias', en: 'Nehemiah' },
  et: { 'pt-br': 'Ester', en: 'Esther' },
  jb: { 'pt-br': 'Jó', en: 'Job' },
  sl: { 'pt-br': 'Salmos', en: 'Psalms' },
  pv: { 'pt-br': 'Provérbios', en: 'Proverbs' },
  ec: { 'pt-br': 'Eclesiastes', en: 'Ecclesiastes' },
  ct: { 'pt-br': 'Cânticos', en: 'Song of Solomon' },
  is: { 'pt-br': 'Isaías', en: 'Isaiah' },
  jr: { 'pt-br': 'Jeremias', en: 'Jeremiah' },
  lm: { 'pt-br': 'Lamentações', en: 'Lamentations' },
  ez: { 'pt-br': 'Ezequiel', en: 'Ezekiel' },
  dn: { 'pt-br': 'Daniel', en: 'Daniel' },
  os: { 'pt-br': 'Oséias', en: 'Hosea' },
  jl: { 'pt-br': 'Joel', en: 'Joel' },
  am: { 'pt-br': 'Amós', en: 'Amos' },
  ob: { 'pt-br': 'Obadias', en: 'Obadiah' },
  jn: { 'pt-br': 'Jonas', en: 'Jonah' },
  mq: { 'pt-br': 'Miquéias', en: 'Micah' },
  na: { 'pt-br': 'Naum', en: 'Nahum' },
  hc: { 'pt-br': 'Habacuque', en: 'Habakkuk' },
  sf: { 'pt-br': 'Sofonias', en: 'Zephaniah' },
  ag: { 'pt-br': 'Ageu', en: 'Haggai' },
  zc: { 'pt-br': 'Zacarias', en: 'Zechariah' },
  ml: { 'pt-br': 'Malaquias', en: 'Malachi' },
  mt: { 'pt-br': 'Mateus', en: 'Matthew' },
  mc: { 'pt-br': 'Marcos', en: 'Mark' },
  lc: { 'pt-br': 'Lucas', en: 'Luke' },
  jo: { 'pt-br': 'João', en: 'John' },
  at: { 'pt-br': 'Atos', en: 'Acts' },
  rm: { 'pt-br': 'Romanos', en: 'Romans' },
  '1co': { 'pt-br': '1 Coríntios', en: '1 Corinthians' },
  '2co': { 'pt-br': '2 Coríntios', en: '2 Corinthians' },
  gl: { 'pt-br': 'Gálatas', en: 'Galatians' },
  ef: { 'pt-br': 'Efésios', en: 'Ephesians' },
  fp: { 'pt-br': 'Filipenses', en: 'Philippians' },
  cl: { 'pt-br': 'Colossenses', en: 'Colossians' },
  '1ts': { 'pt-br': '1 Tessalonicenses', en: '1 Thessalonians' },
  '2ts': { 'pt-br': '2 Tessalonicenses', en: '2 Thessalonians' },
  '1tm': { 'pt-br': '1 Timóteo', en: '1 Timothy' },
  '2tm': { 'pt-br': '2 Timóteo', en: '2 Timothy' },
  tt: { 'pt-br': 'Tito', en: 'Titus' },
  fm: { 'pt-br': 'Filemom', en: 'Philemon' },
  hb: { 'pt-br': 'Hebreus', en: 'Hebrews' },
  tg: { 'pt-br': 'Tiago', en: 'James' },
  '1pe': { 'pt-br': '1 Pedro', en: '1 Peter' },
  '2pe': { 'pt-br': '2 Pedro', en: '2 Peter' },
  '1jo': { 'pt-br': '1 João', en: '1 John' },
  '2jo': { 'pt-br': '2 João', en: '2 John' },
  '3jo': { 'pt-br': '3 João', en: '3 John' },
  jd: { 'pt-br': 'Judas', en: 'Jude' },
  rv: { 'pt-br': 'Apocalipse', en: 'Revelation' },
} as const
